name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        auto-update-conda: true
        activate-environment: base
        use-mamba: true
    - name: Update Conda Environment
      run: conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
